<?php

declare(strict_types=1);

namespace Chunkify\Jobs\Transcoders\TranscoderListResponse;

use Chunkify\ChunkifyError;
use Chunkify\Core\Attributes\Optional;
use Chunkify\Core\Attributes\Required;
use Chunkify\Core\Concerns\SdkModel;
use Chunkify\Core\Contracts\BaseModel;
use Chunkify\Jobs\Transcoders\TranscoderListResponse\Data\Status;

/**
 * @phpstan-import-type ChunkifyErrorShape from \Chunkify\ChunkifyError
 *
 * @phpstan-type DataShape = array{
 *   id: string,
 *   billableTime: int,
 *   chunkEndTime: float,
 *   chunkNumber: int,
 *   chunkStartTime: float,
 *   cpuTime: float,
 *   createdAt: \DateTimeInterface,
 *   fps: float,
 *   frame: int,
 *   jobID: string,
 *   outTime: int,
 *   progress: float,
 *   speed: float,
 *   status: Status|value-of<Status>,
 *   transcoderInstanceID: string,
 *   updatedAt: \DateTimeInterface,
 *   error?: null|ChunkifyError|ChunkifyErrorShape,
 * }
 */
final class Data implements BaseModel
{
    /** @use SdkModel<DataShape> */
    use SdkModel;

    /**
     * Unique identifier of the transcoder.
     */
    #[Required]
    public string $id;

    /**
     * Billable time in seconds.
     */
    #[Required('billable_time')]
    public int $billableTime;

    /**
     * End time of the current chunk in seconds.
     */
    #[Required('chunk_end_time')]
    public float $chunkEndTime;

    /**
     * Number of the chunk being processed.
     */
    #[Required('chunk_number')]
    public int $chunkNumber;

    /**
     * Start time of the current chunk in seconds.
     */
    #[Required('chunk_start_time')]
    public float $chunkStartTime;

    /**
     * CPU time used for transcoding in seconds.
     */
    #[Required('cpu_time')]
    public float $cpuTime;

    /**
     * Timestamp when the status was created.
     */
    #[Required('created_at')]
    public \DateTimeInterface $createdAt;

    /**
     * Current frames per second being processed.
     */
    #[Required]
    public float $fps;

    /**
     * Current frame number being processed.
     */
    #[Required]
    public int $frame;

    /**
     * Unique identifier of the job.
     */
    #[Required('job_id')]
    public string $jobID;

    /**
     * Current output time in seconds.
     */
    #[Required('out_time')]
    public int $outTime;

    /**
     * Progress percentage of the transcoding operation (0-100).
     */
    #[Required]
    public float $progress;

    /**
     * Current processing speed multiplier.
     */
    #[Required]
    public float $speed;

    /**
     * Current status of the transcoder (starting, transcoding, finished, failed).
     *
     * @var value-of<Status> $status
     */
    #[Required(enum: Status::class)]
    public string $status;

    /**
     * Unique identifier of the transcoder instance (generated by the transcoder).
     */
    #[Required('transcoder_instance_id')]
    public string $transcoderInstanceID;

    /**
     * Timestamp when the status was last updated.
     */
    #[Required('updated_at')]
    public \DateTimeInterface $updatedAt;

    /**
     * Error message if the transcoding failed.
     */
    #[Optional]
    public ?ChunkifyError $error;

    /**
     * `new Data()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Data::with(
     *   id: ...,
     *   billableTime: ...,
     *   chunkEndTime: ...,
     *   chunkNumber: ...,
     *   chunkStartTime: ...,
     *   cpuTime: ...,
     *   createdAt: ...,
     *   fps: ...,
     *   frame: ...,
     *   jobID: ...,
     *   outTime: ...,
     *   progress: ...,
     *   speed: ...,
     *   status: ...,
     *   transcoderInstanceID: ...,
     *   updatedAt: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Data)
     *   ->withID(...)
     *   ->withBillableTime(...)
     *   ->withChunkEndTime(...)
     *   ->withChunkNumber(...)
     *   ->withChunkStartTime(...)
     *   ->withCPUTime(...)
     *   ->withCreatedAt(...)
     *   ->withFps(...)
     *   ->withFrame(...)
     *   ->withJobID(...)
     *   ->withOutTime(...)
     *   ->withProgress(...)
     *   ->withSpeed(...)
     *   ->withStatus(...)
     *   ->withTranscoderInstanceID(...)
     *   ->withUpdatedAt(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Status|value-of<Status> $status
     * @param ChunkifyError|ChunkifyErrorShape|null $error
     */
    public static function with(
        string $id,
        int $billableTime,
        float $chunkEndTime,
        int $chunkNumber,
        float $chunkStartTime,
        float $cpuTime,
        \DateTimeInterface $createdAt,
        float $fps,
        int $frame,
        string $jobID,
        int $outTime,
        float $progress,
        float $speed,
        string $transcoderInstanceID,
        \DateTimeInterface $updatedAt,
        Status|string $status = 'pending',
        ChunkifyError|array|null $error = null,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['billableTime'] = $billableTime;
        $self['chunkEndTime'] = $chunkEndTime;
        $self['chunkNumber'] = $chunkNumber;
        $self['chunkStartTime'] = $chunkStartTime;
        $self['cpuTime'] = $cpuTime;
        $self['createdAt'] = $createdAt;
        $self['fps'] = $fps;
        $self['frame'] = $frame;
        $self['jobID'] = $jobID;
        $self['outTime'] = $outTime;
        $self['progress'] = $progress;
        $self['speed'] = $speed;
        $self['status'] = $status;
        $self['transcoderInstanceID'] = $transcoderInstanceID;
        $self['updatedAt'] = $updatedAt;

        null !== $error && $self['error'] = $error;

        return $self;
    }

    /**
     * Unique identifier of the transcoder.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Billable time in seconds.
     */
    public function withBillableTime(int $billableTime): self
    {
        $self = clone $this;
        $self['billableTime'] = $billableTime;

        return $self;
    }

    /**
     * End time of the current chunk in seconds.
     */
    public function withChunkEndTime(float $chunkEndTime): self
    {
        $self = clone $this;
        $self['chunkEndTime'] = $chunkEndTime;

        return $self;
    }

    /**
     * Number of the chunk being processed.
     */
    public function withChunkNumber(int $chunkNumber): self
    {
        $self = clone $this;
        $self['chunkNumber'] = $chunkNumber;

        return $self;
    }

    /**
     * Start time of the current chunk in seconds.
     */
    public function withChunkStartTime(float $chunkStartTime): self
    {
        $self = clone $this;
        $self['chunkStartTime'] = $chunkStartTime;

        return $self;
    }

    /**
     * CPU time used for transcoding in seconds.
     */
    public function withCPUTime(float $cpuTime): self
    {
        $self = clone $this;
        $self['cpuTime'] = $cpuTime;

        return $self;
    }

    /**
     * Timestamp when the status was created.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $self = clone $this;
        $self['createdAt'] = $createdAt;

        return $self;
    }

    /**
     * Current frames per second being processed.
     */
    public function withFps(float $fps): self
    {
        $self = clone $this;
        $self['fps'] = $fps;

        return $self;
    }

    /**
     * Current frame number being processed.
     */
    public function withFrame(int $frame): self
    {
        $self = clone $this;
        $self['frame'] = $frame;

        return $self;
    }

    /**
     * Unique identifier of the job.
     */
    public function withJobID(string $jobID): self
    {
        $self = clone $this;
        $self['jobID'] = $jobID;

        return $self;
    }

    /**
     * Current output time in seconds.
     */
    public function withOutTime(int $outTime): self
    {
        $self = clone $this;
        $self['outTime'] = $outTime;

        return $self;
    }

    /**
     * Progress percentage of the transcoding operation (0-100).
     */
    public function withProgress(float $progress): self
    {
        $self = clone $this;
        $self['progress'] = $progress;

        return $self;
    }

    /**
     * Current processing speed multiplier.
     */
    public function withSpeed(float $speed): self
    {
        $self = clone $this;
        $self['speed'] = $speed;

        return $self;
    }

    /**
     * Current status of the transcoder (starting, transcoding, finished, failed).
     *
     * @param Status|value-of<Status> $status
     */
    public function withStatus(Status|string $status): self
    {
        $self = clone $this;
        $self['status'] = $status;

        return $self;
    }

    /**
     * Unique identifier of the transcoder instance (generated by the transcoder).
     */
    public function withTranscoderInstanceID(string $transcoderInstanceID): self
    {
        $self = clone $this;
        $self['transcoderInstanceID'] = $transcoderInstanceID;

        return $self;
    }

    /**
     * Timestamp when the status was last updated.
     */
    public function withUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $self = clone $this;
        $self['updatedAt'] = $updatedAt;

        return $self;
    }

    /**
     * Error message if the transcoding failed.
     *
     * @param ChunkifyError|ChunkifyErrorShape $error
     */
    public function withError(ChunkifyError|array $error): self
    {
        $self = clone $this;
        $self['error'] = $error;

        return $self;
    }
}
