<?php

declare(strict_types=1);

namespace Chunkify\Webhooks\NewEventWebhookEvent\Data;

use Chunkify\Core\Attributes\Required;
use Chunkify\Core\Concerns\SdkModel;
use Chunkify\Core\Contracts\BaseModel;
use Chunkify\Files\JobFile;
use Chunkify\Jobs\Job;

/**
 * Payload data structure for job.completed events.
 *
 * @phpstan-import-type JobFileShape from \Chunkify\Files\JobFile
 * @phpstan-import-type JobShape from \Chunkify\Jobs\Job
 *
 * @phpstan-type NotificationPayloadJobCompletedShape = array{
 *   files: list<JobFile|JobFileShape>, job: Job|JobShape
 * }
 */
final class NotificationPayloadJobCompleted implements BaseModel
{
    /** @use SdkModel<NotificationPayloadJobCompletedShape> */
    use SdkModel;

    /**
     * List of files generated by the job.
     *
     * @var list<JobFile> $files
     */
    #[Required(list: JobFile::class)]
    public array $files;

    #[Required]
    public Job $job;

    /**
     * `new NotificationPayloadJobCompleted()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * NotificationPayloadJobCompleted::with(files: ..., job: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new NotificationPayloadJobCompleted)->withFiles(...)->withJob(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param list<JobFile|JobFileShape> $files
     * @param Job|JobShape $job
     */
    public static function with(array $files, Job|array $job): self
    {
        $self = new self;

        $self['files'] = $files;
        $self['job'] = $job;

        return $self;
    }

    /**
     * List of files generated by the job.
     *
     * @param list<JobFile|JobFileShape> $files
     */
    public function withFiles(array $files): self
    {
        $self = clone $this;
        $self['files'] = $files;

        return $self;
    }

    /**
     * @param Job|JobShape $job
     */
    public function withJob(Job|array $job): self
    {
        $self = clone $this;
        $self['job'] = $job;

        return $self;
    }
}
